services:
  db:
    image: postgres:17
    container_name: legacy_db
    environment:
      POSTGRES_DB: legacy_payments
      POSTGRES_USER: legacy_user
      POSTGRES_PASSWORD: legacy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./seeder.sql:/docker-entrypoint-initdb.d/02-seeder.sql:ro

  powershell:
    image: mcr.microsoft.com/powershell:7.4-ubuntu-22.04
    container_name: legacy_powershell
    working_dir: /app
    volumes:
      - .:/app
    command: pwsh legacy.ps1

volumes:
  postgres_data: